EXP_NAME: 'SOME_RANDOM_NAME'
RNG_SEED: 1
GPU_ID: '3'
DATASET:
  NAME: CIFAR10 
  ROOT_DIR: 'data'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 10
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
  MODEL_PATH: 'path/to/saved/model'
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True