# EXP_NAME: 'YOUR_EXPERIMENT_NAME'
RNG_SEED: 1
DATASET:
  NAME: MNIST 
  ROOT_DIR: './data'
  VAL_RATIO: 0.1
  AUG_METHOD: 'hflip'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 10
OPTIM:
  TYPE: 'adam'
  BASE_LR: 0.005
  LR_POLICY: none
  LR_MULT: 0.1
  # STEPS: [0, 60, 120, 160, 200] 
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0003
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 1
  IM_SIZE: 32
  EVAL_PERIOD: 2
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
ACTIVE_LEARNING:
  INIT_L_RATIO: 0.001
  BUDGET_SIZE: 60
  # SAMPLING_FN: 'uncertainty'
  MAX_ITER: 5