EXP_NAME: 'SOME_RANDOM_NAME'
RNG_SEED: 1
GPU_ID: '3'
DATASET:
  NAME: CIFAR10 
  ROOT_DIR: 'data'
  VAL_RATIO: 0.1
  AUG_METHOD: 'horizontalflip'
MODEL:
  TYPE: resnet18
  NUM_CLASSES: 10
OPTIM:
  TYPE: 'sgd'
  BASE_LR: 0.1
  LR_POLICY: steps
  STEPS: [0] #[0, 30, 60, 90]
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0005
  GAMMA: 0.1
TRAIN:
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 32
  EVAL_PERIOD: 10
TEST:
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True